name: Build and Test Api
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/fully-automated-golang-api-app-deployment-pipeline:$(git rev-parse --short "$GITHUB_SHA")
    - name: Push the Docker image
      id: push 
      run: docker push ${{ secrets.DOCKER_USER }}/fully-automated-golang-api-app-deployment-pipeline:$(git rev-parse --short "$GITHUB_SHA")